# Generated by Django 2.1.1 on 2018-10-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181006_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cuisine',
            field=models.IntegerField(choices=[(1, 'Chinese'), (2, 'North Indian'), (3, 'South Indian'), (4, 'Italian')]),
        ),
    ]
